name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main]

jobs:
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./data-volumes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: data-volumes/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test || echo "No tests found"
